[project]
name = "ha-grocery-deals"
version = "1.0.2-dev0"
description = "Home Assistant integration for Grocery Deals supermarket price comparison and discount aggregator."
authors = [
    {name = "FaserF", email = "github@fabiseitz.de"}
]
readme = "README.md"
requires-python = ">=3.14"

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B", "C4"]
ignore = ["E501", "B008", "SIM102", "SIM105", "SIM117", "E402", "B017", "B904", "ARG001", "RUF012", "DTZ003", "DTZ007", "DTZ001", "DTZ005", "BLE001", "S110", "S112"]

[tool.mypy]
explicit_package_bases = true
python_version = "3.14"
show_error_codes = true
follow_imports = "silent"
ignore_missing_imports = true
strict_equality = true
warn_incomplete_stub = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_subclassing_any = false
disallow_untyped_calls = false
disallow_untyped_decorators = false
disallow_untyped_defs = true
disable_error_code = ["misc", "call-arg", "import-untyped"]


[tool.pytest.ini_options]
testpaths = [
    "tests",
]
norecursedirs = [
    ".git",
    "testing_config",
]
asyncio_mode = "auto"
pythonpath = ["stubs"]
